export const TEST_CASES = new Map<string, Set<string>>();
TEST_CASES.set('abbr', new Set(['basic']));
TEST_CASES.set('accordion', new Set(['basic', 'header', 'headlines']));
TEST_CASES.set('alert', new Set(['basic', 'card-msg', 'html']));
TEST_CASES.set('badge', new Set(['basic', 'button']));
TEST_CASES.set('breadcrumb', new Set(['basic']));
TEST_CASES.set('button', new Set(['basic', 'icon-only', 'icons', 'width']));
TEST_CASES.set('button-group', new Set(['basic']));
TEST_CASES.set('button-link', new Set(['basic', 'icons', 'image', 'target']));
TEST_CASES.set('card', new Set(['basic', 'confirm', 'flex', 'selection']));
TEST_CASES.set('details', new Set(['basic']));
// TEST_CASES.set('form', new Set(['basic']));
TEST_CASES.set('heading', new Set(['basic', 'badged', 'paragraph']));
TEST_CASES.set('icon', new Set(['basic']));
TEST_CASES.set('indented-text', new Set(['basic']));
// TEST_CASES.set('input-checkbox', new Set(['basic']));
// TEST_CASES.set('input-color', new Set(['basic']));
// TEST_CASES.set('input-date', new Set(['basic']));
// TEST_CASES.set('input-email', new Set(['basic']));
// TEST_CASES.set('input-file', new Set(['basic']));
// TEST_CASES.set('input-number', new Set(['basic']));
// TEST_CASES.set('input-password', new Set(['basic']));
// TEST_CASES.set('input-range', new Set(['basic']));
// TEST_CASES.set('input-text', new Set(['basic']));
TEST_CASES.set('link', new Set(['basic', 'icons', 'image', 'target']));
TEST_CASES.set('link-button', new Set(['basic']));
// TEST_CASES.set('link-group', new Set(['basic']));
TEST_CASES.set('nav', new Set(['basic', 'horizontal']));
TEST_CASES.set('pagination', new Set(['basic']));
TEST_CASES.set('progress', new Set(['basic']));
// TEST_CASES.set('select', new Set(['basic']));
TEST_CASES.set('skip-nav', new Set(['basic']));
TEST_CASES.set('spin', new Set(['basic']));
TEST_CASES.set('table', new Set(['render-cell', 'sort-date']));
TEST_CASES.set('textarea', new Set(['basic', 'adjust-height', 'disabled', 'placeholder', 'readonly', 'resize', 'rows']));
// TEST_CASES.set('toast', new Set(['basic']));
TEST_CASES.set('tooltip', new Set(['basic']));
TEST_CASES.set('version', new Set(['basic', 'context']));
