name: Visual regression tests

on:
  schedule:
    - cron: '30 0,6,12,18 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test-matrix:
    continue-on-error: true
    strategy:
      matrix:
        os: [macos-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
        theme: [bmf, bpa, bzst, desy-v2, ecl-ec, ecl-eu, itzbund, mapz, th, zoll-v2]
        # theme: [bamf, bmf, bpa, bzst, desy-v1, desy-v2, ecl-ec, ecl-eu, itzbund, mapz, th, zoll-v2]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # - uses: actions/cache@v3
      #   with:
      #     path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
      #     key: ${{ runner.os }}-pnpm-store
      #     restore-keys: ${{ runner.os }}-pnpm-store

      - name: Install
        run: pnpm i

      - name: Test
        continue-on-error: true
        run: npx playwright test -g ${{ matrix.theme }}

      # - name: Move test results
      #   continue-on-error: true
      #   run: |
      #     mkdir test-results-
      #     mv test-results test-results-/${{ matrix.os }}
      #     mv test-results- test-results

      # - name: Git config
      #   run: |
      #     git config --local user.email "github@martinoppitz.com"
      #     git config --local user.name "Martin Oppitz"
      #     # git config pull.ff only
      #     # git config pull.rebase true
      #     git config pull.rebase false

      # # - name: Commit changed test results
      # #   continue-on-error: true
      # #   run: |
      # #     git add --force test-results/${{ matrix.os }}/**/*${{ matrix.theme }}*
      # #     git status
      # #     git commit -m "chore: store test results - ${{ matrix.os }} ${{ matrix.theme }}"

      # - name: Commit changed test snapshots
      #   continue-on-error: true
      #   run: |
      #     git add --force tests/**/*${{ matrix.theme }}*
      #     git status
      #     git commit -m "chore: store updated test snapshots - ${{ matrix.os }} ${{ matrix.theme }}"

      # - uses: 1itachi/sleep-random@v1.0.0
      #   with:
      #     minutes: '1'
      #     random: 'true'

      # - name: Git pull
      #   run: git pull

      # - uses: ad-m/github-push-action@master
      #   continue-on-error: true
      #   with:
      #     github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #     branch: ${{ github.ref }}

      # - uses: 1itachi/sleep-random@v1.0.0
      #   if: failure()
      #   with:
      #     minutes: '1'
      #     random: 'true'

      # - name: Git pull
      #   if: failure()
      #   run: git pull

      # - uses: ad-m/github-push-action@master
      #   if: failure()
      #   with:
      #     github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #     branch: ${{ github.ref }}
